name: Make CI
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: ソースコードを取得
        uses: actions/checkout@v7

      - name: 開発環境を確認
        run: |
          g++ --version
          make --version
      - name: ビルド
        run: make
        
      - name: テスト
        run: make test